name: MacOS Monterey Swift Release CI

on:
  push:
    branches: [development, main]
  pull_request:
    branches: [development, main]

jobs:

  exec-mac-ci-release:
    runs-on: macos-12

    steps:
      - uses: swift-actions/setup-swift@v1
        with:
          swift-version: "5.7"

      #- name: Install guunits
      #  uses: mipalgu/install-guunits@main

      - name: Setup SSH Key
        uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.WORKFLOWS_SSH_PRIVATE_KEY }} 

      - name: Install Dependencies
        run: |
          rm /usr/local/bin/2to3-3.11 /usr/local/bin/idle3.11 /usr/local/bin/pydoc3.11 /usr/local/bin/python3.11 /usr/local/bin/python3.11-config
          brew update
          brew install --overwrite gtk4 glib glib-networking gobject-introspection pkg-config atk

      - name: Checkout repo
        uses: actions/checkout@v2
      
      #- name: Reconfigure Private Repo URLs
      #  run: sed -i 's/git@github.com:/https:\/\/${{ secrets.ACCESS_TOKEN }}@github.com\//g' Package.swift

      - name: Release Build
        run: xcrun --toolchain swift 5.7 --run swift build -c release

      - name: Release Test
        run: xcrun --toolchain swift 5.7 --run swift test -c release
